### ISSUE TITLE
Won't run on Ubuntu 14.10 with python 3.4.2 

### ISSUE THREAD

**Issue by anithri** [acrisci/i3-dstatus#1]
Regrettably I know nothing of how python finds and loads files.  I looked for google help on the error and I couldn't find anything that I could understand except one import trick that at least caused a failure _later_ than the original.

Out of the box error

```
$ ./i3-dstatus clock
Traceback (most recent call last):
  File "./i3-dstatus", line 3, in <module>
    import glib, json, dbus, dbus.service, sys, os, threading, subprocess
ImportError: No module named 'glib'
```

the furthest I got with tinkering was to change the import statements

``` python
#!/usr/bin/env python3
from gi.repository import GLib
import json, dbus, dbus.service, sys, os, threading, subprocess
```

and I get a little further, as it at least starts the output chain

```
 $ ./i3-dstatus clock
{"version":1}
[
[]
Traceback (most recent call last):
  File "./i3-dstatus", line 91, in <module>
    main = glib.MainLoop()
NameError: name 'glib' is not defined
```

Let me know if I can provide more information or test out a solution

**Comment by acrisci** [comment]
I was doing some experiments with the old GLib python library and accidently committed it. I'll switch it back to the new bindings.

You'll need `python-gobject` from your package manager. I still need to work on the distribution component and give better error messages.

**Comment by anithri** [comment]
That worked great, thanks!
