### ISSUE TITLE
Paint blocks on the root window (like conky)

### ISSUE THREAD

**Issue by acrisci** [acrisci/i3-dstatus#10]
[Conky](https://github.com/brndnmtthws/conky) is a system monitor that paints its information on the root window.

I would like to give people the ability to paint the content of blocks on the root window.

This may end up turning into a new project due to the extra dependencies.

Here's how I think it should work. Each block that wants to paint on the root window sets a member on the block which contains html markup. This markup is inserted into a `<div>` within a main container. The main container is rendered with webkit and painted on the root window.

Would anyone find this sort of thing useful? Does anyone have any suggestions for how the interface should work?

**Comment by anithri** [comment]
A lot of my playing around with i3-dstatus has been to try different combinations of fonts and colors (love the pango markup!) to achieve gauges and things like that.  So the allure of being able to draw using html/css is strong.  Even without JS there's a ton of power there, and with JS....

The only issue I can see with that general idea are the system tray(whatever its called) and workspace list. 

And I think it's a pretty next gen idea.  It reshapes the problem into one that utilizes existing skills, it adds a profound amount of possibilities when it comes to html/css/js as far as animations, alternating blocks, scrolling and click events.  And offers some interesting and ways to use svg and emoji, even images or sounds inline.  It's actually a more interesting idea the more I think about it.

**Comment by acrisci** [comment]
I think you might be under the impression that I was suggesting we paint on i3bar itself. While that is a good idea for a project (it was attempted by the now unmaintained [Candybar](https://github.com/Lokaltog/candybar) project), what I'm suggesting here is painting on the desktop background portion of the screen.

**Comment by anithri** [comment]
OK, sounds interesting, but I can't quite see the use case unless it's a conky replacement.  What do you have in mind for it?
