### ISSUE TITLE
[meta] API Rewrite

### ISSUE THREAD

**Issue by AstraLuma** [acrisci/i3-dstatus#12]
In discussions with @acrisci about a new API interface, we'd both like to see a more overt, structured, and explicit API over D-Bus. More object-oriented and REST-inspired. To that end, here is my proposal for the new API.

This should be considered a target to aim for, not documentation on how anything works. This bug is meant to be a reference for other implementation bugs and pull requests.
# D-Bus
## `/com/dubstepdish/i3dstatus`

Implements: `com.dubstepdish.i3dstatus.Manager`, [`org.freedesktop.DBus.ObjectManager`](http://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces-objectmanager)

This is the top-level object for applications. With it, they can create, delete, search for, and get events about blocks. There's also a handful of utility methods.
### `com.dubstepdish.i3dstatus.Manager`
- method `CreateBlock(Dict<String, Variant> values)` -> `ObjectPath block`: Creates a new block with the values given. The path is autogenerated and is guaranteed to be unique only during the lifetime of the block.
- method `DeleteBlock(ObjectPath block)`: Removes a block. Any further calls to it are immediately invalid and it is removed from the bar.
- method `FindBlock(String name, String instance)` -. `ObjectPath block`: Finds an existing block.
- signal `BlockAdded(ObjectPath block)`: Fired when a block is added to the bar (ie created)
- signal `BlockRemoved(ObjectPath block)`: Fired when a block is removed from the bar (ie deleted)
- signal `BlockChanged(ObjectPath block)`: Fired when a block has changed (ie, fires its `PropertiesChanged` event)
- method `GetConfig(String generator)` -> `Dict<String, Variant>`: Get a generator's configuration block from i3-dstatus's configuration
## `/com/dubstepdish/i3dstatus/{{BlockID}}`

Implements: `com.dubstepdish.i3dstatus.Block`, [`org.freedesktop.DBus.Properties`](http://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces-properties)

Simply a bag of properties describing a single block.

It is considered Good Practice to have `block.name` match the name of the script and the name of the configuration block, but this isn't enforced.
### `com.dubstepdish.i3dstatus.Block`
- properties `full_text`, `short_text`, `color`, `min_width`, `align`, `name`, `instance`, `urgent`, `separator`, `separator_block_width`, `markup`: Same as they are in the [i3bar protocol spec](http://i3wm.org/docs/i3bar-protocol.html#_blocks_in_detail).
- property `Integer ordinal`: A number describing where a block occurs. Lower numbers appear sooner (under `i3bar`, farther to the right) than those with higher numbers.
- method `Get(String name)` -> `Variant value`: Convenience method for `org.freedesktop.DBus.Properties.Get`
- method `Set(String name, Variant value)`: Convenience method for `org.freedesktop.DBus.Properties.Set`
- method `Update(Dict<String, Variant> values)`: Update multiple properties at once, issuing only one `org.freedesktop.DBus.Properties.PropertiesChanged` signal for it
- method `GetProp(String name)` -> `Variant value`: Get a dynamic property (eg `_ethernet_vendor`)
- method `SetProp(String name, Variant value)`: Set a dynamic property
- signal `Clicked(Int x, Int y, Unsigned button)`: User clicked on a block
# Command line

`i3-dstatus [--config|-c <config file>]`
- `--config`/`-c`: Specify configuration file to use (defaults to `~/.i3-dstatus`)
# Configuration

The change here is in the `general` block.
- `general.gendirs`: List of directories to search for generators in
- `general.order`: Specify a default order for blocks, by name/instance

An order block may look something like:

``` yaml
general:
  order:
    - clock
    - load
    - [freespace, /]
    - [freespace, /home]
    - [ip, wlan0]
    - battery
```

Blocks matching these criteria are assigned an ordinal following 1, 2, 3, ..... All blocks that do not have a defined ordinal will appear in an undefined order after those that do.

i3-dstatus will also search for executables matching the name of the configured blocks in `general.gendirs`. If one of them happens to match, it is run at startup. No further process management is performed.

**Comment by AstraLuma** [comment]
The one problem I see with this is that it forces recurring scripts (not long-running) to first find the block and then call on it. But this is easily fixed with a `FindOrCreate` method on D-Bus or utility libraries.

(It's reasonable that the same script would do initial block set up as the one that does the update.)

**Comment by acrisci** [comment]
First of all, I want to avoid breaking changes to the api. I also generally like how things work now, so the goal should be to add on extra stuff that is useful in some situations rather than a complete redesign.

So how about instead of changing the interface to `com.dubstepdish.i3dstatus.Manager` we leave it how it is at `com.dubstepdish.i3dstatus`? This interface should also include the `get_config` and `show_block` method, so it does not break anything.

I kind of like the underscore case because that looks better in pretty much every programming language.

**Comment by astronouth7303** [comment]
There's a migration path for interfaces: Run the new methods on the new interface, and the old ones on the old one. This is what deprecation policies are for.

As for naming conventions, I was following those suggested in the spec and used by every other D-Bus application.

**Comment by AstraLuma** [comment]
If you like how things are now, I'll just fork and do my own thing. Why didn't you say so sooner?

**Comment by acrisci** [comment]
I'd rather implement this without removing every feature and replacing it with something new.
