### ISSUE TITLE
New release and battery issue

### ISSUE THREAD

**Issue by norpol** [acrisci/i3-dstatus#14]
Hi, I've just realized that i3-dstatus on GitHub already contains some code for displaying battery status - but the one on pypi is still missing battery.py, could you maybe do a new release?

**Comment by norpol** [comment]
Ok, the battery thing breaks after few minutes with the text below instead of percentage:

`BAT1 <dbus_next.signature.Variant object at 0x0000000>`

**Comment by acrisci** [comment]
Yeah pypi version is kind of old.

I need to do a release of i3ipc-python before I can release this.

I'll look into the battery issue too.

**Comment by norpol** [comment]
Thank you, I have two batteries inside my laptop btw - couldn't figure out how to get both displaying at the same time too.

I hope I can get some contributions ready, still trying to wrap my head around the dbus stuff though.

**Comment by acrisci** [comment]
I wrote the dbus library too so if you have questions with that, I'll support that as well.

I'm still around and I use this statusline every day so I'll keep doing releases.
