### ISSUE TITLE
Please add in a placeholder to cli or configfile

### ISSUE THREAD

**Issue by anithri** [acrisci/i3-dstatus#2]
I'm very impressed with how this works.  My use case isn't addressed yet.  I don't think there's a reliable way to position specific blocks used by external programs.

The winning proposition(s) of this program is the way it separates the aggregation from the generation, and allows for all sorts of new ideas in status bars, simply through the dbus message passing and the separation of concern that allows.  but there isn't a reliable way to determine order.

maybe passing a name on the cli that isn't a generator creates an named empty placeholder to be filled in when the other daemons finally get started, or scheduled updates start coming in,   alternatively use the config file to determine order of output.

**Comment by acrisci** [comment]
Thanks for your input. This is something that I've thought about and I want to really get it right so it's as easy as possible to control the order.

The placeholder idea as it is is a bit awkward. It removes the ability to throw errors when a generator is requested but not found. It also makes it difficult to explain to people what exactly is being passed on the command line. Maybe we can give the argument a prefix like `placeholder:custom_script` or something. I'll have to think about it.

Right now you can pass an absolute path to i3-dstatus and it will run this script as a generator. I wish there was some way to ensure the correct order for scripts like this, but I don't think there is a way to check which process sent a particular dbus message. Right now this is done with the convention that the name of the block must match the file name of the generator.

Another thing to consider is that I would like to leave open the possibility for one script to be responsible for multiple blocks, and this would require a more flexible system.

Right now I'm leaning towards one of two things.

One way would be to have a positional indexing system that is given within the block. Each block has a position index and the order of the blocks will be determined by sorting them on the index.

Another thing I was thinking of is to have some sort of before/after declaration in the block. So for instance you can give the block a member like `"after":"mediaplayer"` and the block always be positioned after the mediaplayer block. We could also do a `before` member.

What do you think?

**Comment by anithri** [comment]
I agree about placeholder, explicit in the configuration file is the way to go.  An array variable containing the names of the blocks (or zones which I'll come back in a bit) to establish the order, and those using the same names coming from the generators seems like a fine convention to me.

I like the concept of multiple blocks from a single generator.  it will make some things I want to do easier, at least until i3-bar gets better color controls.  For instance I have a display about my current
working git repo that shows red yellow, green and blue colored displays of how many files have changed in order to help me remember to commit on a regular basis.  So having 1 generator being able to do small segments strung together is important.  I was thinking that zones is a good name for what may be 1 or more json blocks.  It's relatively easy to implement if you can flatten the array 1 level, 

The last point I'll make in this favor is that we are not talking about many blocks, mostly 3-12 each I'd guess.  With the order safely selected from the config file, won't it be faster to reload the config file instead of messing with `after` and `before`?

**Comment by acrisci** [comment]
The config entry sounds like a good idea.

I want to do a combination of position indexing and the config entry. We will add a `general` member to the config that has an `order` member which is an array of strings.

```
general:
    order: [ mediaplayer, clock, clipboard ]
```

The index in the array is now the position index for the block (e.g., mediaplayer = 0, clock = 1, ...).

It doesn't matter if the entry in the array is the name of a generator or not. Any incoming block with a name member that matches an array entry will have their index default to the array index.

If no `order` is found, the default will be the current behavior of displaying in the order given on the command line.

Any generator can override the configured order by giving their block a `ds_position` member with the desired index.

I think this behavior also leaves room for `after` and `before` to be implemented if that is needed.

What do you think?
