### ISSUE TITLE
Contribution policy for generators?

### ISSUE THREAD

**Issue by anithri** [acrisci/i3-dstatus#3]
This is working great for me so far, so I'm going to port my old i3blocks scripts over.  They'll be bash and/or ruby scripts, and so far you only have python in your repo.

I'll make a different generators project if you decide to keep it python only, but I'll be using i3-dstatus as the aggregator for i3bar.

thanks for the great work and the timely responses to my issues.

**Comment by acrisci** [comment]
The goal for distribution is to use pip for installation of everything, so for that reason, python3 is preferred.

I'll also accept bash as long as it doesn't require anything that is not commonly installed on a Linux distribution with dbus support.

**Comment by anithri** [comment]
Ok, I'll post my repo for ruby based generators when I have something to show.  

Thanks again!

**Comment by acrisci** [comment]
I think it might make sense to have some kind of "contrib" directory sort of like how i3blocks has for scripts that won't be distributed with pip. It might be better to do it that way than to have separate repositories.

**Comment by anithri** [comment]
I can easily do that for my shell scripts.  It's harder for the ruby daemons since I'd need to have external libraries installed, and that is easier to distribute using the ruby gems process.
