### ISSUE TITLE
scheduler?

### ISSUE THREAD

**Issue by anithri** [acrisci/i3-dstatus#5]
a lot of my generators will have a different schedule in when they need to run.  Every 15 minutes, on the hour, every minute...  I'm wondering if there is value in exploring different ways to have a central scheduler, and have it register schedules and then send a trigger method at the appropriate time.

**Comment by acrisci** [comment]
For this particular use case, I think it's best to have the scheduler within the generator itself. In most cases, a simple timer is enough. For more advanced cases, look for a scheduler library. [Here is a scheduler](https://github.com/dbader/schedule) for python that looks pretty nice.

What advantages would a central scheduler have?

**Comment by anithri** [comment]
My thoughts were mostly along the line of where should I put timing/interval/at times.  Does it belong in the generator?  the aggregator?  but I can pass a value in the config to set the right time settings without further complicating the central aggregator
